name: Build master

on:
  push:
  pull_request:

jobs:
  build_master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo xargs --arg-file=${{ github.workspace }}/.github/workflows/build-dependencies.txt apt-get install -qq

        # the versions in ubuntu repos are too old
        sudo python3 -m pip install --quiet meson ninja

        # confirm that the tools are installed
        # the build system doesn't fail when they are not
        meson --version
        ninja --version
    - name: Install Catch2
      run: |
        # ubuntu only packages catch-1.12.2, need catch-2.13.8
        wget --quiet https://github.com/catchorg/Catch2/releases/download/v2.13.8/catch.hpp
        sudo mkdir /usr/include/catch2
        sudo mv catch.hpp /usr/include/catch2
    - name: GCC
      run: |
        mkdir ./test/build_gcc
        cd ./test/build_gcc
        CC=gcc CXX=g++ LD=ld.bfd meson ..
        ninja
        ./test_suite
    - name: Clang
      run: |
        mkdir ./test/build_clang
        cd ./test/build_clang
        CC=clang CXX=clang++ LD=ld.lld meson ..
        ninja
        ./test_suite
